{{- $fullName := include "practica24.rabbitmq.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
spec:
  ports:
  - port: {{ .Values.rabbitmq.service.port }}
  selector:
    app: {{ $fullName }}
  clusterIP: None