{{- $fullName := include "practica24.serverapp.fullname" . -}}
{{- $rabbitName := include "practica24.rabbitmq.fullname" . -}}
{{- $mongoName := include "practica24.mongo.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $fullName }}
  strategy:
    type: Recreate
  template: 
    metadata:
      labels:
        app: {{ $fullName }}
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
      containers:
      - image: {{ .Values.serverapp.image.repository }}
        name: {{ $fullName }}
        env:
        - name: RABBITMQ_URL
          value: amqp://{{ $rabbitName }}
        - name: MONGODB_URL
          value: mongodb://{{ $mongoName }}
        ports:
        - containerPort: {{ .Values.serverapp.container.port }}
        securityContext:
          runAsUser: {{ .Values.serverapp.container.securityContext.runAsUser }}
          allowPrivilegeEscalation: {{ .Values.serverapp.container.securityContext.allowPrivilegeEscalation }}